# Generated by Django 4.2.23 on 2025-08-07 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_pet', models.CharField(max_length=100)),
                ('telefone', models.CharField(max_length=20)),
                ('dia_reserva', models.DateField()),
                ('observacoes', models.TextField()),
            ],
        ),
    ]
